/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.gradleup.shadow") version "9.2.2"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/groups/public/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }

    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    api(libs.org.bstats.bstats.bukkit)
    api(libs.com.zaxxer.hikaricp)
    api(libs.com.github.oshi.oshi.core)
    compileOnly(libs.org.apache.logging.log4j.log4j.core)
    compileOnly(libs.org.apache.logging.log4j.log4j.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.com.github.seeseemelk.mockbukkit.v1.v21)
    testImplementation(libs.org.xerial.sqlite.jdbc)
    testImplementation(libs.org.slf4j.slf4j.simple)
    testImplementation(libs.net.bytebuddy.byte.buddy)
    testImplementation(libs.net.bytebuddy.byte.buddy.agent)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.fastasyncworldedit.fastasyncworldedit.core)
    compileOnly(libs.com.fastasyncworldedit.fastasyncworldedit.bukkit)
    compileOnly(libs.com.github.deadsilenceiv.advancedchestsapi)
}

group = "net.coreprotect"
version = "23.1-VANGUARD"
description = "coreprotect"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
